# Generated by Django 4.1.2 on 2022-10-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="carom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="carom/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "table_size",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Persent"
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="detection.projection_method",
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
    ]
