# Generated by Django 4.1.2 on 2022-10-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="projection_method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="NAME")),
                (
                    "value",
                    models.PositiveSmallIntegerField(null=True, verbose_name="VALUE"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="carom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        upload_to="carom/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "table_size",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="Persent"
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="u_img.projection_method",
                        verbose_name="Type",
                    ),
                ),
            ],
        ),
    ]
