# Generated by Django 4.1.2 on 2022-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="carom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="carom/", verbose_name="Image")),
                ("guide", models.JSONField(default=dict, verbose_name="Guide JSON")),
                (
                    "detect_state",
                    models.CharField(
                        choices=[
                            ("N", "None"),
                            ("A", "Accepted"),
                            ("P", "Progress"),
                            ("D", "Done"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Work State",
                    ),
                ),
            ],
        ),
    ]
