# Generated by Django 4.1.2 on 2022-11-22 06:20

from django.db import migrations
import django_db_views.migration_functions
import django_db_views.operations


class Migration(migrations.Migration):

    dependencies = [
        ("u_img", "0001_initial"),
    ]

    operations = [
        django_db_views.operations.ViewRunPython(
            code=django_db_views.migration_functions.ForwardViewMigration(
                'SELECT "u_img_carom_data"."img_id", "u_img_carom_img"."img", "u_img_carom_data"."guide", "u_img_carom_data"."detect_state", "u_img_carom_data"."img_id" AS "id", "u_img_carom_img"."img" AS "img" FROM "u_img_carom_data" INNER JOIN "u_img_carom_img" ON ("u_img_carom_data"."img_id" = "u_img_carom_img"."id")',
                "CaromTable",
                engine="django.db.backends.sqlite3",
            ),
            reverse_code=django_db_views.migration_functions.BackwardViewMigration(
                "", "CaromTable", engine="django.db.backends.sqlite3"
            ),
            atomic=False,
        ),
    ]
