# Generated by Django 4.1.2 on 2022-10-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="projection_method",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="NAME")),
                (
                    "value",
                    models.PositiveSmallIntegerField(null=True, verbose_name="VALUE"),
                ),
            ],
        ),
    ]
