# Generated by Django 4.1.2 on 2022-11-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balls_coord",
            name="coord",
            field=models.JSONField(default="{}", verbose_name="COORDINATE JSON"),
        ),
    ]
