# Generated by Django 4.1.2 on 2022-11-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_alter_balls_coord_coord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balls_coord",
            name="coord",
            field=models.JSONField(default=dict, verbose_name="COORDINATE JSON"),
        ),
    ]
