# Generated by Django 4.1.2 on 2022-11-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_alter_balls_coord_coord"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="balls_coord",
            constraint=models.UniqueConstraint(
                fields=("carom",), name="unique solution"
            ),
        ),
    ]
